### ISSUE TITLE
only extracting a share of the consultation 

### ISSUE THREAD

**Issue by lululililu** [FelixRech/hys_scraper#3]
Hello,

Apologize for my post in advance, first time posting here and absolutely no experience in code. 

I managed to use your scraper, but it does not extract and download all the consultations, only a share of them. As for example, the consultation with ID 31514984 (https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13539-EU-Youth-Strategy-2019-2027-interim-evaluation/feedback_en?p_id=31514984)  retrieves only 10 feedbacks from 36.

Amazing tool by the way, thanks a lot!

**Comment by felixrech** [comment]
Hi lululililu,

I tried to reproduce your problem and everything seems to be working correctly. You can see the results I get when scraping the initiative you mentioned in this [demo](https://gist.github.com/felixrech/90a68205b613cddb184f54b51b31a67f).

What I can only assume happened is that you looked into the `attachments/` folder and found only 10 PDF files there. This would mean the scraper working as intended, as only ten of the feedback submissions have a PDF attached to them. The remaining feedback submissions do not and hence no PDF file is created. Information on each feedback submission (everything shown in the browser) is in the `feedbacks.csv` file, which you can open using a programming language (e.g. Python+Pandas as in the attached demo) or spreadsheet program like Excel or Google Sheets. The text displayed in the browser for each feedback submission corresponds to the 'feedback' column of the `feedbacks.csv` file.

Hope this helps, if you still have problems, feel free to reopen this issue!
